version: '3.9'

services:
  webapp:
    container_name: web_container
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:80
    depends_on:
      - postgres_db

  postgres_db:
    image: postgres
    container_name: db_container
    restart: always
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data: 

networks:
  default:
    driver: bridge
